services:
  fastapi-backend:
    container_name: coursework-backend-dev
    build:
      context: ../backend
      dockerfile: ./docker/dev.Dockerfile
    env_file:
      - ../backend/env/.env.dev
    volumes:
      - ../backend/logging/logs:/app/logging/logs
      - ../backend/src:/app/src
    restart: always
    ports:
      - 8000:8000
    networks:
      - app-network

  frontend:
    container_name: vite-frontend-dev
    build:
      context: ../frontend
      dockerfile: ../docker/dev.Dockerfile
    volumes:
      - ../frontend/src:/app/src
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    networks:
      - app-network
    command: ["npm", "run", "dev"]
    restart: on-failure


networks:
  app-network:
    driver: bridge
