services:
  fastapi-backend:
    container_name: coursework-backend-prod
    build:
      context: ../backend
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - ../backend/env/.env.prod
    restart: always
    ports:
      - 8000:8000
    networks:
      - app-network

  react-frontend:
    container_name: coursework-frontend-prod
    build:
      context: ../frontend
      dockerfile: ../frontend/docker/prod.Dockerfile
    env_file:
      - ../frontend/env/.env.prod
    volumes:
      - /app/node_modules
    restart: always
    ports:
      - 80:80
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
