/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchEntryImport } from './routes/search-entry'
import { Route as EntriesImport } from './routes/entries'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SearchEntryRoute = SearchEntryImport.update({
  id: '/search-entry',
  path: '/search-entry',
  getParentRoute: () => rootRoute,
} as any)

const EntriesRoute = EntriesImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/entries': {
      id: '/entries'
      path: '/entries'
      fullPath: '/entries'
      preLoaderRoute: typeof EntriesImport
      parentRoute: typeof rootRoute
    }
    '/search-entry': {
      id: '/search-entry'
      path: '/search-entry'
      fullPath: '/search-entry'
      preLoaderRoute: typeof SearchEntryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entries': typeof EntriesRoute
  '/search-entry': typeof SearchEntryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entries': typeof EntriesRoute
  '/search-entry': typeof SearchEntryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/entries': typeof EntriesRoute
  '/search-entry': typeof SearchEntryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entries' | '/search-entry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entries' | '/search-entry'
  id: '__root__' | '/' | '/entries' | '/search-entry'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntriesRoute: typeof EntriesRoute
  SearchEntryRoute: typeof SearchEntryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntriesRoute: EntriesRoute,
  SearchEntryRoute: SearchEntryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/entries",
        "/search-entry"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/entries": {
      "filePath": "entries.tsx"
    },
    "/search-entry": {
      "filePath": "search-entry.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
