import { IconChartBar, IconListDetails, IconSearch } from "@tabler/icons-react"
import { Nutrient, NutrientUnit, Sidebar, BackendNutrientTarget, BackendFoodEntry } from "./types"
import { subDays } from "date-fns"

export enum RouteUrl {
    DASHBOARD = "/",
    SEARCH_ENTRY = "/search-entry",
    ENTRIES = "/entries",
}

export const SIDEBAR = {
    main: [
        {
            title: "Dashboard",
            url: RouteUrl.DASHBOARD,
            icon: IconChartBar,
        },
        {
            title: "Search Entry",
            url: RouteUrl.SEARCH_ENTRY,
            icon: IconSearch,
        },
        {
            title: "Entries",
            url: RouteUrl.ENTRIES,
            icon: IconListDetails,
        }
    ],
} satisfies Sidebar

export const USER_ID = 1
export const DATE_FORMAT = "dd/MM/yyyy"

export const FOOD_ENTRIES: BackendFoodEntry[] = [
    {
        id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Chicken Breast",
        timestamp: new Date(),
        nutrients: [
            {
                id: 1,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.CALORIES,
                quantity: 500,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 2,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.PROTEIN,
                quantity: 60,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 3,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.CARBOHYDRATES,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 4,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.FAT,
                quantity: 26,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 5,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 6,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 7,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.VITAMIN_D,
                quantity: 0.2,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 8,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 1,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Salmon Fillet",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 1)),
        nutrients: [
            {
                id: 9,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.CALORIES,
                quantity: 400,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 10,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.PROTEIN,
                quantity: 50,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 11,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.CARBOHYDRATES,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 12,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.FAT,
                quantity: 20,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 13,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 14,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 15,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.VITAMIN_D,
                quantity: 15,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 16,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 2,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Brown Rice",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 2)),
        nutrients: [
            {
                id: 17,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.CALORIES,
                quantity: 215,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 18,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.PROTEIN,
                quantity: 5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 19,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.CARBOHYDRATES,
                quantity: 45,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 20,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.FAT,
                quantity: 1.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 21,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 22,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 23,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 24,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 3,
                name: Nutrient.FIBRE,
                quantity: 3.5,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Broccoli",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 3)),
        nutrients: [
            {
                id: 25,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.CALORIES,
                quantity: 55,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 26,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.PROTEIN,
                quantity: 4.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 27,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.CARBOHYDRATES,
                quantity: 11,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 28,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.FAT,
                quantity: 0.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 29,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.SUGAR,
                quantity: 2,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 30,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.VITAMIN_C,
                quantity: 89,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 31,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 32,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 4,
                name: Nutrient.FIBRE,
                quantity: 3.8,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Almonds",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 4)),
        nutrients: [
            {
                id: 33,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.CALORIES,
                quantity: 575,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 34,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.PROTEIN,
                quantity: 21,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 35,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.CARBOHYDRATES,
                quantity: 22,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 36,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.FAT,
                quantity: 49,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 37,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.SUGAR,
                quantity: 4.4,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 38,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 39,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 40,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 5,
                name: Nutrient.FIBRE,
                quantity: 12.5,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Greek Yogurt",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 5)),
        nutrients: [
            {
                id: 41,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.CALORIES,
                quantity: 100,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 42,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.PROTEIN,
                quantity: 10,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 43,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.CARBOHYDRATES,
                quantity: 4,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 44,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.FAT,
                quantity: 5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 45,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.SUGAR,
                quantity: 3,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 46,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 47,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.VITAMIN_D,
                quantity: 1,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 48,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 6,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Apple",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 6)),
        nutrients: [
            {
                id: 49,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.CALORIES,
                quantity: 95,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 50,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.PROTEIN,
                quantity: 0.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 51,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.CARBOHYDRATES,
                quantity: 25,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 52,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.FAT,
                quantity: 0.3,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 53,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.SUGAR,
                quantity: 19,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 54,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.VITAMIN_C,
                quantity: 8.4,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 55,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 56,
                createdAt: new Date(),
                updatedAt: new Date(),
                foodEntryId: 7,
                name: Nutrient.FIBRE,
                quantity: 4.4,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
]

export const TARGETS: BackendNutrientTarget[] = [
    {
        id: 1,
        createdAt: subDays(new Date(), 2),
        updatedAt: subDays(new Date(), 2),
        userId: USER_ID,
        name: Nutrient.CALORIES,
        quantity: 2500,
        unit: NutrientUnit.CALORIES,
        isLowerBound: false,
    },
    {
        id: 2,
        createdAt: subDays(new Date(), 2),
        updatedAt: subDays(new Date(), 2),
        userId: USER_ID,
        name: Nutrient.PROTEIN,
        quantity: 200,
        unit: NutrientUnit.GRAMS,
        isLowerBound: true,
    },
    {
        id: 3,
        createdAt: subDays(new Date(), 2),
        updatedAt: subDays(new Date(), 2),
        userId: USER_ID,
        name: Nutrient.FAT,
        quantity: 25,
        unit: NutrientUnit.GRAMS,
        isLowerBound: false,
    },
    {
        id: 4,
        createdAt: subDays(new Date(), 2),
        updatedAt: subDays(new Date(), 2),
        userId: USER_ID,
        name: Nutrient.SUGAR,
        quantity: 25,
        unit: NutrientUnit.GRAMS,
        isLowerBound: false,
    },
]

export enum QueryKey {
    USDA_FOOD = "usda/food",
    USER = "macromotions/user",
    FOOD_ENTRY = "macromotions/food-entry",
}
