import { IconChartBar, IconListDetails, IconSearch } from "@tabler/icons-react"
import { Nutrient, NutrientUnit, Sidebar, NutrientTarget, DatabaseFoodEntry } from "./types"

export enum RouteUrl {
    DASHBOARD = "/",
    SEARCH_ENTRY = "/search-entry",
    ENTRIES = "/entries",
}

export const SIDEBAR = {
    main: [
        {
            title: "Dashboard",
            url: RouteUrl.DASHBOARD,
            icon: IconChartBar,
        },
        {
            title: "Search Entry",
            url: RouteUrl.SEARCH_ENTRY,
            icon: IconSearch,
        },
        {
            title: "Entries",
            url: RouteUrl.ENTRIES,
            icon: IconListDetails,
        }
    ],
} satisfies Sidebar

export const USER_ID = 1

export const FOOD_ENTRIES: DatabaseFoodEntry[] = [
    {
        id: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Chicken Breast",
        timestamp: new Date(),
        nutrients: [
            {
                id: 1,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.CALORIES,
                quantity: 500,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 2,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.PROTEIN,
                quantity: 60,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 3,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.CARBOHYDRATES,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 4,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.FAT,
                quantity: 26,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 5,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 6,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 7,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.VITAMIN_D,
                quantity: 0.2,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 8,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 1,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Salmon Fillet",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 1)),
        nutrients: [
            {
                id: 9,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.CALORIES,
                quantity: 400,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 10,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.PROTEIN,
                quantity: 50,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 11,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.CARBOHYDRATES,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 12,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.FAT,
                quantity: 20,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 13,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 14,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 15,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.VITAMIN_D,
                quantity: 15,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 16,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 2,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Brown Rice",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 2)),
        nutrients: [
            {
                id: 17,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.CALORIES,
                quantity: 215,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 18,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.PROTEIN,
                quantity: 5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 19,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.CARBOHYDRATES,
                quantity: 45,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 20,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.FAT,
                quantity: 1.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 21,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.SUGAR,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 22,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 23,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 24,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 3,
                name: Nutrient.FIBRE,
                quantity: 3.5,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Broccoli",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 3)),
        nutrients: [
            {
                id: 25,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.CALORIES,
                quantity: 55,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 26,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.PROTEIN,
                quantity: 4.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 27,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.CARBOHYDRATES,
                quantity: 11,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 28,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.FAT,
                quantity: 0.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 29,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.SUGAR,
                quantity: 2,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 30,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.VITAMIN_C,
                quantity: 89,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 31,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 32,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 4,
                name: Nutrient.FIBRE,
                quantity: 3.8,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Almonds",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 4)),
        nutrients: [
            {
                id: 33,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.CALORIES,
                quantity: 575,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 34,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.PROTEIN,
                quantity: 21,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 35,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.CARBOHYDRATES,
                quantity: 22,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 36,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.FAT,
                quantity: 49,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 37,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.SUGAR,
                quantity: 4.4,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 38,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 39,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 40,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 5,
                name: Nutrient.FIBRE,
                quantity: 12.5,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Greek Yogurt",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 5)),
        nutrients: [
            {
                id: 41,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.CALORIES,
                quantity: 100,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 42,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.PROTEIN,
                quantity: 10,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 43,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.CARBOHYDRATES,
                quantity: 4,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 44,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.FAT,
                quantity: 5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 45,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.SUGAR,
                quantity: 3,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 46,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.VITAMIN_C,
                quantity: 0,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 47,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.VITAMIN_D,
                quantity: 1,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 48,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 6,
                name: Nutrient.FIBRE,
                quantity: 0,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
    {
        id: USER_ID,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: USER_ID,
        name: "Apple",
        timestamp: new Date(new Date().setDate(new Date().getDate() - 6)),
        nutrients: [
            {
                id: 49,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.CALORIES,
                quantity: 95,
                unit: NutrientUnit.CALORIES,
            },
            {
                id: 50,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.PROTEIN,
                quantity: 0.5,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 51,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.CARBOHYDRATES,
                quantity: 25,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 52,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.FAT,
                quantity: 0.3,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 53,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.SUGAR,
                quantity: 19,
                unit: NutrientUnit.GRAMS,
            },
            {
                id: 54,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.VITAMIN_C,
                quantity: 8.4,
                unit: NutrientUnit.MILLI_GRAMS,
            },
            {
                id: 55,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.VITAMIN_D,
                quantity: 0,
                unit: NutrientUnit.MICRO_GRAMS,
            },
            {
                id: 56,
                created_at: new Date(),
                updated_at: new Date(),
                food_entry_id: 7,
                name: Nutrient.FIBRE,
                quantity: 4.4,
                unit: NutrientUnit.GRAMS,
            },
        ],
    },
]

export const TARGETS: NutrientTarget[] = [
    {
        name: Nutrient.CALORIES,
        quantity: 3000,
        unit: NutrientUnit.CALORIES,
    },
    {
        name: Nutrient.PROTEIN,
        quantity: 200,
        unit: NutrientUnit.GRAMS,
    },
    {
        name: Nutrient.FAT,
        quantity: 25,
        unit: NutrientUnit.GRAMS,
    },
    {
        name: Nutrient.SUGAR,
        quantity: 25,
        unit: NutrientUnit.GRAMS,
    },
]

export const TARGET_COMPARATORS_LOOKUP: Record<Nutrient, (quantity: number, target: number) => boolean> = {
    "calories": (quantity: number, target: number) => quantity >= target,
    "protein": (quantity: number, target: number) => quantity >= target,
    "carbohydrates": (quantity: number, target: number) => quantity <= target,
    "fat": (quantity: number, target: number) => quantity <= target,
    "sugar": (quantity: number, target: number) => quantity <= target,
    "vitamin_c": (quantity: number, target: number) => quantity >= target,
    "vitamin_d": (quantity: number, target: number) => quantity >= target,
    "fibre": (quantity: number, target: number) => quantity > target,
}

export enum QueryKey {
    USDA_FOOD = "usda/food",
    USER = "macromotions/user"
}
