name: CI Pipeline

on:
  push:
    branches:
      - "*" # Trigger on push to any branch
  pull_request:
    branches:
      - "*" # Trigger on pull request to any branch

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository code

      - name: Run echo command
        run: echo "GitHub Actions workflow is running!"
