name: CI Pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Run Vitest Tests
        run: |
          cd frontend
          npm test

      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-reports
