name: Vitest Unit Tests

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
    push:
      branches:
        - dev
        - prod

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend
          bun install

      - name: Run Vitest
        run: |
          cd frontend
          bun run test
