name: Vitest Unit Tests

on:
    pull_request:
      types:
        - opened
        - synchronize
        - reopened
    push:
      branches:
        - dev
        - prod

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd frontend
          bun install

      - name: Run unit tests
        run: |
          cd frontend
          bun run test
